### ISSUE TITLE
Consider using flux

### ISSUE THREAD

**Issue by fxfactorial** [fxfactorial/silicondzor#13]

**Comment by HaykoKoryun** [comment]
or WebComponents/Google Polymer for that matter, would give the site a nice lick of paint with not too much effort (although Google's Polymer is currently patchy as npm modules, I am having a headache right now migrating from bower to npm)

**Comment by fxfactorial** [comment]
I don't follow. Flux is about data, polymer is about UI and would require getting rid of React.

**Comment by HaykoKoryun** [comment]
That'll teach me to not skim read project overviews, had a very cursory look at the Flux project to have an idea as to what the issue was about and got the wrong impression. Don't mind me 😝

**Comment by fxfactorial** [comment]
@HaykoKoryun Don't leave, stick around and improve it :) I'm doing a big refactor/improvement at the moment

**Comment by HaykoKoryun** [comment]
Might jump in when time permits :)

**Comment by fxfactorial** [comment]
Using mobx instead of flux.
