### ISSUE TITLE
Programmatically get access token every X period of time

### ISSUE THREAD

**Issue by fxfactorial** [fxfactorial/silicondzor#22]
@rht implemented getting events from Facebook programmatically but to use a token you apparently need to get it from FB with an HTTP request. The credentials for this request can come from environment variables. 

http://stackoverflow.com/questions/12948809/trying-to-get-app-access-token

So the flow should be that every X period of time our app does this HTTP request which sets a variable which our app uses currently as `FB_ITERATE_TOKEN`.

**Comment by rht** [comment]
Ah right, the token should be generated just before the graph request. In a min.

**Comment by fxfactorial** [comment]
Implemented in https://github.com/fxfactorial/silicondzor/pull/23
