### ISSUE TITLE
Option for compact list/linear view instead of table view

### ISSUE THREAD

**Issue by rht** [fxfactorial/silicondzor#25]
e.g. https://www.techmeme.com/events, http://www.oneviewcalendar.com/ (https://news.ycombinator.com/item?id=11846108), http://www.techconferences.io/ (https://news.ycombinator.com/item?id=12943889)

**Comment by fxfactorial** [comment]
True but the other tabs, like `agenda` tab make it linear. (Plus this project serves pedagogical purposes so using a third party react component is part of the deal)

**Comment by rht** [comment]
Wait, there is already the agenda view.

**Comment by fxfactorial** [comment]
@rht yea, so I'll close this.
