### ISSUE TITLE
Events time seems off? 

### ISSUE THREAD

**Issue by fxfactorial** [fxfactorial/silicondzor#26]
Thanks to @rht we have events programmatically sourced from various FB groups, hurrah! 

One small thing I'm noticing though, many events say they are at early hours, like 5AM when I suspect them mean to say 5PM. This is probably a simple date mistake in our code, should be an easy fix.

**Comment by rht** [comment]
Hmm the date is stored on unixtime after already taking into account of the timezone. So it is shown with the timezone of the server. This is to be fixed with adding a `+04:00` offset in the frontend, and reverse offset when the event is manually entered.

**Comment by fxfactorial** [comment]
Fixed
