### ISSUE TITLE
Automatically translate Events? 

### ISSUE THREAD

**Issue by fxfactorial** [fxfactorial/silicondzor#27]
Many events that we source are in different languages. Apparently there is a free translation service via  https://translate.yandex.com, they have an API. 

Its not clear though how we should store it though.....concat original description plus translations into one long string might be the easiest way at the moment.

**Comment by edgarkhanzadian** [comment]
we can make title_en, title_am, title_ru in silicondzor SQL table. When we fetch data from FB or somebody inputs an event, server first will find out in what language it is written, then translate it in two other languages and then put it in sql table

**Comment by fxfactorial** [comment]
Okay good idea, but then what do we display? Do we take the three strings and concat them? Then show that?

**Comment by edgarkhanzadian** [comment]
yes, we can do that using "/" sign
Example: {eng} / {arm} / {rus}

**Comment by fxfactorial** [comment]
@edgarkhanzadyan Okay! Good idea, I look forward to your pull request with the code :)

**Comment by rht** [comment]
This might be a relevant read: https://arxiv.org/abs/1609.08144#table10 for the current state of reaching human-parity for machine-translation.

**Comment by fxfactorial** [comment]
Implemented
