### ISSUE TITLE
Let end user know what groups are being sourced

### ISSUE THREAD

**Issue by fxfactorial** [fxfactorial/silicondzor#28]
We should let the end user know what groups we are sourcing information from, this can be done with a visual queue on the front end. 

Now we'll really need to make a separate table for the event sourcing groups and their respective IDs.

**Comment by rht** [comment]
You could reuse the existing event table. The `creator` field is filled with the group name (but since it is integer, it should have been group id), and the `id` field contains the host and the event id, e.g. `fb-216966745417656`.

**Comment by fxfactorial** [comment]
Implemented
