### ISSUE TITLE
Use HTTPS

### ISSUE THREAD

**Issue by fxfactorial** [fxfactorial/silicondzor#3]
Make sure site works on HTTPS as a best practice example, need to use letencrypt.

**Comment by rht** [comment]
The lib for this: https://github.com/Daplie/node-letsencrypt (including periodic certificate renewal).

**Comment by fxfactorial** [comment]
@rht good idea, but would first like to have lower level commits before using this higher level lib

**Comment by rht** [comment]
Actually, `node-letsencrypt` is the lower-level lib that powers `letsencrypt-express` (I have a local branch that still needs to be ironed out, brb).
