### ISSUE TITLE
email verify link

### ISSUE THREAD

**Issue by akadevil** [fxfactorial/silicondzor#39]
Guys just trying to register and verify my email, but something went wrong and verify email comes with
"localhost:9090/verify-account/......"
https://github.com/fxfactorial/silicondzor/blob/master/backend/server.js#L29-L32
https://github.com/fxfactorial/silicondzor/blob/master/backend/env.js#L6

**Comment by fxfactorial** [comment]
good point, I think that was fixed. it was because it was using the wrong environ variable. thanks!
