### ISSUE TITLE
Use  Eventbrite API to auto populate events

### ISSUE THREAD

**Issue by fxfactorial** [fxfactorial/silicondzor#8]
See discussion here: https://github.com/fxfactorial/silicondzor/issues/6

**Comment by rht** [comment]
I have the data further cleaned in this format: `curl 'https://www.eventbriteapi.com/v3/events/search/?token=0x5f3759df&location.latitude=40.1792&location.longitude=44.4991&location.within=50km' | jq '.events' | jq 'map({"name":.name.text, "description":.description.text, "start":.start.utc, "end":.end.utc, "status":.status, "url":.url})'` (haven't got the nodejs run on my nixos box yet -- nodejs >=7 is too bleeding edge lol)

**Comment by fxfactorial** [comment]
Nice. 

Yea, the site is running very bleeding edge, 7.3 with` --harmony_async_await`.

**Comment by rht** [comment]
(I'm still reading about the implementation for the async/await) It does use `libuv`, doesn't it?
There are only few web frameworks that use `libuv`, e.g. h20, sanic.

**Comment by fxfactorial** [comment]
Ya, although I wouldn't call node a framework,  more like a decked out JavaScript runtime.

**Comment by fxfactorial** [comment]
@rht yea, node uses https://github.com/libuv/libuv . I've been thinking of using the lib as well, for some OCaml ideas.
